repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
        - id: check-merge-conflict
        - id: check-xml
        - id: check-yaml
        - id: check-json
        - id: no-commit-to-branch
          args: ["--branch=main"]
        - id: end-of-file-fixer
        - id: fix-byte-order-marker
        - id: trailing-whitespace
        - id: check-executables-have-shebangs
        - id: check-shebang-scripts-are-executable

  -   repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v17.0.6
      hooks:
        - id: clang-format
          types_or: [javascript]

  -   repo: https://github.com/google/yapf
      rev: v0.40.2
      hooks:
        - id: yapf

  -   repo: https://github.com/executablebooks/mdformat
      rev: 0.7.17
      hooks:
        - id: mdformat
